name: SDK PR report

on:
  pull_request:
    branches:
      - DEV-354-sdk-pipeline

env:
  PYTHON: 3.7.12
  POETRY: 1.1.12
  UNIT_TEST_REPORT: unit-test-report.xml

concurrency:
  group: cord-client-${{ github.ref }}-pr
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY }}
          virtualenvs-in-project: true

      - name: Check cache
        id: cached-poetry
        uses: actions/cache@v2
        with:
          path: .venv
          key: unit-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON }}

      - name: Install dependencies
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest tests --verbose --junitxml=${{ env.UNIT_TEST_REPORT }}

      - name: Upload report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ env.UNIT_TEST_REPORT }}
          path: ${{ env.UNIT_TEST_REPORT }}

      - name: Publish unit test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{ env.UNIT_TEST_REPORT }}
          check_name: Unit test report